from .schemas import (
    Paper,
    PaperSearchResult,
    Claim,
    ClaimExtractionResult,
    ClaimType,
    EvidenceType,
    ValidationStatus,
    CitationValidation,
    ClaimValidation,
    GraphNode,
    GraphEdge,
    KnowledgeGraph,
    SearchRequest,
    AnalyzeRequest,
    AnalyzeResponse,
    DeepResearchRequest,
)

# Knowledge Graph schemas (PRD implementation)
from .kg_schemas import (
    ClaimNode,
    ClaimEdge,
    SourcePaperMetadata,
    ExternalSourceMetadata,
    ExtractionMetadata,
    BuildRun,
    BuildRunConfig,
    BuildRunProgress,
    ProvenanceChain,
    ProvenanceResult,
    ClaimSearchFilters,
    ClaimSearchRequest,
    ClaimSearchResult,
    ClaimSearchResponse,
    GraphStatistics,
    GraphBuildRequest,
    BuildStatusResponse,
    ClaimDetailResponse,
    SupportResponse,
    RefreshResponse,
    generate_claim_id,
    generate_edge_id,
)

__all__ = [
    # Legacy schemas
    "Paper",
    "PaperSearchResult",
    "Claim",
    "ClaimExtractionResult",
    "ClaimType",
    "EvidenceType",
    "ValidationStatus",
    "CitationValidation",
    "ClaimValidation",
    "GraphNode",
    "GraphEdge",
    "KnowledgeGraph",
    "SearchRequest",
    "AnalyzeRequest",
    "AnalyzeResponse",
    "DeepResearchRequest",
    # Knowledge Graph schemas
    "ClaimNode",
    "ClaimEdge",
    "SourcePaperMetadata",
    "ExternalSourceMetadata",
    "ExtractionMetadata",
    "BuildRun",
    "BuildRunConfig",
    "BuildRunProgress",
    "ProvenanceChain",
    "ProvenanceResult",
    "ClaimSearchFilters",
    "ClaimSearchRequest",
    "ClaimSearchResult",
    "ClaimSearchResponse",
    "GraphStatistics",
    "GraphBuildRequest",
    "BuildStatusResponse",
    "ClaimDetailResponse",
    "SupportResponse",
    "RefreshResponse",
    "generate_claim_id",
    "generate_edge_id",
]
